Update to 0.22
rmrk-team/evm-sample-contracts pull request #13
Opened 2023-01-04 14:10 UTC by steven2308

2023-01-04 22:01 UTC, ThunderDeliverer requested changes
Nothing major, just a few minor fixes 😄

2023-01-05 14:47 UTC, steven2308 commented on package.json
> +    "@rmrk-team/evm-contracts": "^0.22.0"
It wasn't released at that point but yeah. I think I'll generate another minor soon (after adding emotables) and will update then.

2023-01-05 14:50 UTC, steven2308 commented on package.json
> +    "@rmrk-team/evm-contracts": "^0.22.0"
May I merge now? It still looks like changes are requested.

2023-01-05 20:44 UTC, ThunderDeliverer commented on package.json
> +    "@rmrk-team/evm-contracts": "^0.22.0"
Yeah, sorry, it's been a crazy day and I forgot to mark this as approved 🙈

2023-01-05 20:45 UTC, merged